export const DIALOG_STEPS = {
    BASIC_INFO: 'BASIC_INFO',
    DETAILS: 'DETAILS',
    SUBMIT: 'SUBMIT'
};

export const DIALOG_STEPS_ORDER = [
    DIALOG_STEPS.BASIC_INFO,
    DIALOG_STEPS.DETAILS,
    DIALOG_STEPS.SUBMIT
]; 